name: Pull Request Checks

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Dependency updates check
        uses: UpSync-Dev/sbt-dependency-updates-action@v1
